#include "memoria_mobile.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(expr) do { if (!(expr)) { fprintf(stderr,"CHECK failed: %s (%s:%d)\n",#expr,__FILE__,__LINE__); return 1; } } while (0)

static memoria_mobile_status learn(memoria_mobile_handle *h, const char *json, memoria_mobile_buffer *out) {
    memoria_mobile_buffer in = {(const uint8_t *)json, strlen(json)};
    return memoria_mobile_learn_turn_json(h, in, out);
}

static int contains(memoria_mobile_buffer b, const char *needle) {
    return b.data && strstr((const char *)b.data, needle) != NULL;
}

static int assert_snapshot_policy(memoria_mobile_handle *h) {
    memoria_mobile_buffer req = {(const uint8_t *)"{}", 2};
    memoria_mobile_buffer out = {0};
    CHECK(memoria_mobile_export_snapshot_json(h, req, &out) == MEMORIA_MOBILE_OK);
    CHECK(contains(out, "\"memory_id\":\"assistant-fact\""));
    CHECK(contains(out, "\"namespace\":\"policy\""));
    CHECK(contains(out, "\"role\":\"assistant\""));
    CHECK(contains(out, "\"text\":\"device = ready\""));
    CHECK(contains(out, "\"source_type\":\"assistant_generated\""));
    CHECK(contains(out, "\"memory_id\":\"user-confirmation\""));
    CHECK(contains(out, "user-confirmation#relation:0"));
    CHECK(!contains(out, "assistant-fact#relation:0"));
    memoria_mobile_free_buffer(out);
    return 0;
}

int main(void) {
    const char *dir = "./tmp-mobile-assistant-promotion";
    memoria_mobile_handle *h = NULL;
    memoria_mobile_buffer out = {0};
    (void)system("rm -rf ./tmp-mobile-assistant-promotion");

    CHECK(memoria_mobile_open(dir, "org-assistant-promotion", &h) == MEMORIA_MOBILE_OK);

    /* A syntactically valid fact generated by the assistant remains a durable
     * turn, but it is not materialized into the trusted relation graph. */
    CHECK(learn(h,
        "{\"role\":\"assistant\",\"text\":\"device = ready\",\"memory_id\":\"assistant-fact\","
        "\"namespace\":\"policy\",\"order\":1}", &out) == MEMORIA_MOBILE_OK);
    CHECK(contains(out, "\"stored_memory_ids\":[\"assistant-fact\"]"));
    CHECK(contains(out, "\"relations\":[]"));
    CHECK(contains(out, "\"unresolved\":true"));
    CHECK(!contains(out, "assistant-fact#relation:0"));
    memoria_mobile_free_buffer(out); out = (memoria_mobile_buffer){0};

    /* The same semantic claim becomes graph-eligible when supplied as user
     * evidence. Confirmation is a new provenance-bearing memory, not a mutation
     * that retroactively upgrades the assistant turn. */
    CHECK(learn(h,
        "{\"role\":\"user\",\"text\":\"device = ready\",\"memory_id\":\"user-confirmation\","
        "\"namespace\":\"policy\",\"order\":2}", &out) == MEMORIA_MOBILE_OK);
    CHECK(contains(out, "user-confirmation#relation:0"));
    memoria_mobile_free_buffer(out); out = (memoria_mobile_buffer){0};

    CHECK(assert_snapshot_policy(h) == 0);
    CHECK(memoria_mobile_flush(h) == MEMORIA_MOBILE_OK);
    memoria_mobile_close(h); h = NULL;

    CHECK(memoria_mobile_open(dir, "org-assistant-promotion", &h) == MEMORIA_MOBILE_OK);
    CHECK(assert_snapshot_policy(h) == 0);

    memoria_mobile_close(h);
    (void)system("rm -rf ./tmp-mobile-assistant-promotion");
    return 0;
}
